work-flow.yml

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -10,18 +10,42 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+      # שלב 1: Checkout code
       - name: Checkout code
         uses: actions/checkout@v3
 
+      # שלב 2: Set up Docker
       - name: Set up Docker
         uses: docker/setup-buildx-action@v2
 
+      # שלב 3: Run Docker Compose
       - name: Run Docker Compose
         id: docker
-        run: docker-compose up --build --abort-on-container-exit
-        continue-on-error: true  # ממשיכים גם אם exit 1
+        run: docker-compose up -d --build
+        continue-on-error: false  # אם exit 1
 
-      - name: Check exit code
+     # שלב 4: Test API - קבלת כל הסטודנטים
+      - name: Test Get All Students
+        run: |
+          for i in {1..10}; do
+            STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost/api/getstudents)
+            echo "Attempt $i - Status code: $STATUS"
+
+            if [ "$STATUS" -eq 200 ]; then
+              echo "API is up!"
+              exit 0
+            fi
+
+            echo "Waiting for API..."
+            sleep 5
+          done
+
+          echo "Test failed: API did not become ready in time"
+          exit 1
+
+
+      # שלב 5: Send email if any step failed
+      - name: Send failure email
         if: ${{ failure() }}
         uses: dawidd6/action-send-mail@v3
         with:
@@ -30,7 +54,25 @@ jobs:
           username: ${{ secrets.SMTP_USER }}
           password: ${{ secrets.SMTP_PASSWORD }}
           subject: "Workflow Failed"
-          body: "Docker Compose test failed! Check GitHub Actions logs."
+          body: "Docker Compose or API test failed! Check GitHub Actions logs."
           to: batziona99@gmail.com
           from: ${{ secrets.SMTP_USER }}
           secure: true
+        
+      - name: Login to Docker Hub
+        if: success()
+        uses: docker/login-action@v2
+        with:
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_TOKEN }}
+
+      - name: Build and Push Image
+        if: success()
+        run: |
+          docker build -t bzl123/ci-cd-final_project:latest .
+          docker push bzl123/ci-cd-final_project:latest
+      
+         #   שלב 6: Shutdown Docker Compose
+      - name: Shutdown Docker Compose
+        if: always()
+        run: docker-compose down
